In [12]:
import pandas as pd
import numpy as np
from math import sin, cos, sqrt, atan2, radians

In [13]:
df = pd.read_csv('Accidentes.csv',sep=';', decimal='.')

In [14]:
df.head()

,Unnamed: 0,FECHA,RANGO HORARIO,DIA SEMANA,DISTRITO,LUGAR ACCIDENTE,Nº,Nº PARTE,CPFA Granizo,CPFA Hielo,...,CPSV Seca Y Limpia,Nº VICTIMAS,TIPO ACCIDENTE,Tipo Vehiculo,TIPO PERSONA,SEXO,LESIVIDAD,Tramo Edad,Latitude,Longitude
0,0,20/11/2014,DE 9:00 A 9:59,JUEVES,CHAMARTIN,AUTOVIA M-30 CALZADA 2 KM.,32300,2014/10641,NO,NO,...,SI,1.0,COLISIÓN DOBLE,MOTOCICLETA,CONDUCTOR,HOMBRE,HL,DE 21 A 24 AÑOS,40.483873,-3.673592
1,1,04/03/2014,DE 13:00 A 13:59,MARTES,VICALVARO,AVENIDA DE LA GRAN VIA DEL ESTE - CALLE DE LA ...,0,2014/2147,NO,NO,...,SI,4.0,COLISIÓN DOBLE,TURISMO,VIAJERO,MUJER,HL,DE 18 A 20 AÑOS,40.398454,-3.601018
2,2,26/05/2018,DE 00:00 A 00:59,SABADO,ARGANZUELA,CALLE DE EROS - CALLE DE LA ESTRELLA HADAR,0,2018/5408,NO,NO,...,SI,4.0,ATROPELLO,NO ASIGNADO,PEATON,HOMBRE,HL,DE 35 A 39 AÑOS,40.393845,-3.680282
3,3,25/02/2010,DE 14:00 A 14:59,JUEVES,CARABANCHEL,CALLE DE BELZUNEGUI - CALLE DE CARCASTILLO,0,2010/1766,NO,NO,...,NO,1.0,COLISIÓN DOBLE,MOTOCICLETA,CONDUCTOR,HOMBRE,HL,DE 30 A 34 ANOS,40.377139,-3.739303
4,4,17/07/2012,DE 18:00 A 18:59,MARTES,MORATALAZ,AVENIDA DEL DOCTOR GARCIA TAPIA - AUTOVIA M-40,0,2012/6707,NO,NO,...,SI,3.0,COLISIÓN DOBLE,FURGONETA,CONDUCTOR,HOMBRE,IL,DE 21 A 24 AÑOS,40.410009,-3.641304

In [15]:
df_ocio = pd.read_csv('Coordenadas_ocio.csv',sep=';', decimal='.')

In [16]:
df_ocio.head()

   Latidud_ocio  Longitud_ocio
0     40.565647      -3.913978
1     40.055614      -3.604527
2     40.424492      -3.691446
3     40.420115      -3.700815
4     40.453986      -3.694140

In [17]:
def distancia_ocio(long1,lat1,long2,lat2):
    R = 6373.0
    lat1 = radians(lat1)
    lon1 = radians(long1)
    lat2 = radians(lat2)
    lon2 = radians(long2)
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    distance = R * c
    return distance

In [18]:
def comparador(row):
    lat = row['Latitude']
    long = row['Longitude']
    v = list()
    for i in range(len(df_ocio)):
        c = distancia_ocio(df_ocio['Longitud_ocio'][i],df_ocio['Latidud_ocio'][i], long, lat )
        v.append(c)
    return min(v)

In [19]:
df['Distancia ocio Km'] = df[['Latitude','Longitude']].apply(lambda row: comparador(row), axis=1)

In [20]:
df.head()

,Unnamed: 0,FECHA,RANGO HORARIO,DIA SEMANA,DISTRITO,LUGAR ACCIDENTE,Nº,Nº PARTE,CPFA Granizo,CPFA Hielo,...,Nº VICTIMAS,TIPO ACCIDENTE,Tipo Vehiculo,TIPO PERSONA,SEXO,LESIVIDAD,Tramo Edad,Latitude,Longitude,Distancia ocio Km
0,0,20/11/2014,DE 9:00 A 9:59,JUEVES,CHAMARTIN,AUTOVIA M-30 CALZADA 2 KM.,32300,2014/10641,NO,NO,...,1.0,COLISIÓN DOBLE,MOTOCICLETA,CONDUCTOR,HOMBRE,HL,DE 21 A 24 AÑOS,40.483873,-3.673592,1.508801
1,1,04/03/2014,DE 13:00 A 13:59,MARTES,VICALVARO,AVENIDA DE LA GRAN VIA DEL ESTE - CALLE DE LA ...,0,2014/2147,NO,NO,...,4.0,COLISIÓN DOBLE,TURISMO,VIAJERO,MUJER,HL,DE 18 A 20 AÑOS,40.398454,-3.601018,2.790873
2,2,26/05/2018,DE 00:00 A 00:59,SABADO,ARGANZUELA,CALLE DE EROS - CALLE DE LA ESTRELLA HADAR,0,2018/5408,NO,NO,...,4.0,ATROPELLO,NO ASIGNADO,PEATON,HOMBRE,HL,DE 35 A 39 AÑOS,40.393845,-3.680282,0.948289
3,3,25/02/2010,DE 14:00 A 14:59,JUEVES,CARABANCHEL,CALLE DE BELZUNEGUI - CALLE DE CARCASTILLO,0,2010/1766,NO,NO,...,1.0,COLISIÓN DOBLE,MOTOCICLETA,CONDUCTOR,HOMBRE,HL,DE 30 A 34 ANOS,40.377139,-3.739303,0.984928
4,4,17/07/2012,DE 18:00 A 18:59,MARTES,MORATALAZ,AVENIDA DEL DOCTOR GARCIA TAPIA - AUTOVIA M-40,0,2012/6707,NO,NO,...,3.0,COLISIÓN DOBLE,FURGONETA,CONDUCTOR,HOMBRE,IL,DE 21 A 24 AÑOS,40.410009,-3.641304,1.041850

In [22]:
df['Lejania ocio']=''
for x in range(len(df)):
    if df['Distancia ocio Km'][x]<0.2:
        df['Lejania ocio'][x]='Muy cerca'
    elif df['Distancia ocio Km'][x]>=0.2 and df['Distancia ocio Km'][x]<0.5:
        df['Lejania ocio'][x]='Cerca'
    elif df['Distancia ocio Km'][x]>=0.5 and df['Distancia ocio Km'][x]<1:
        df['Lejania ocio'][x]='lejos'
    else:
        df['Lejania ocio'][x]='muy lejos'

C:\Users\juanc\anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\juanc\anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\juanc\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\juanc\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [23]:
df.head(100)

,Unnamed: 0,FECHA,RANGO HORARIO,DIA SEMANA,DISTRITO,LUGAR ACCIDENTE,Nº,Nº PARTE,CPFA Granizo,CPFA Hielo,...,TIPO ACCIDENTE,Tipo Vehiculo,TIPO PERSONA,SEXO,LESIVIDAD,Tramo Edad,Latitude,Longitude,Distancia ocio Km,Lejania ocio
0,0,20/11/2014,DE 9:00 A 9:59,JUEVES,CHAMARTIN,AUTOVIA M-30 CALZADA 2 KM.,32300,2014/10641,NO,NO,...,COLISIÓN DOBLE,MOTOCICLETA,CONDUCTOR,HOMBRE,HL,DE 21 A 24 AÑOS,40.483873,-3.673592,1.508801,muy lejos
1,1,04/03/2014,DE 13:00 A 13:59,MARTES,VICALVARO,AVENIDA DE LA GRAN VIA DEL ESTE - CALLE DE LA ...,0,2014/2147,NO,NO,...,COLISIÓN DOBLE,TURISMO,VIAJERO,MUJER,HL,DE 18 A 20 AÑOS,40.398454,-3.601018,2.790873,muy lejos
2,2,26/05/2018,DE 00:00 A 00:59,SABADO,ARGANZUELA,CALLE DE EROS - CALLE DE LA ESTRELLA HADAR,0,2018/5408,NO,NO,...,ATROPELLO,NO ASIGNADO,PEATON,HOMBRE,HL,DE 35 A 39 AÑOS,40.393845,-3.680282,0.948289,lejos
3,3,25/02/2010,DE 14:00 A 14:59,JUEVES,CARABANCHEL,CALLE DE BELZUNEGUI - CALLE DE CARCASTILLO,0,2010/1766,NO,NO,...,COLISIÓN DOBLE,MOTOCICLETA,CONDUCTOR,HOMBRE,HL,DE 30 A 34 ANOS,40.377139,-3.739303,0.984928,lejos
4,4,17/07/2012,DE 18:00 A 18:59,MARTES,MORATALAZ,AVENIDA DEL DOCTOR GARCIA TAPIA - AUTOVIA M-40,0,2012/6707,NO,NO,...,COLISIÓN DOBLE,FURGONETA,CONDUCTOR,HOMBRE,IL,DE 21 A 24 AÑOS,40.410009,-3.641304,1.041850,muy lejos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,29/01/2015,DE 12:00 A 12:59,JUEVES,CIUDAD LINEAL,CALLE DE ANGEL GORDILLO - CALLE DE ARTURO SORIA,0,2015/947,NO,NO,...,COLISIÓN DOBLE,TURISMO,VIAJERO,MUJER,HL,DE 35 A 39 AÑOS,40.464180,-3.665403,1.191172,muy lejos
96,96,23/11/2018,DE 14:00 A 14:59,VIERNES,CHAMBERI,CALLE DE SAGASTA,13,2018/14552,NO,NO,...,CAÍDA BICICLETA,BICICLETA,CONDUCTOR,HOMBRE,HL,DE 18 A 20 AÑOS,40.428791,-3.699966,0.133558,Muy cerca
97,97,18/12/2018,DE 17:00 A 17:59,MARTES,TETUAN,CALLE DEL MARQUES DE VIANA,11,2018/16267,NO,NO,...,CAÍDA MOTOCICLETA,MOTOCICLETA,CONDUCTOR,HOMBRE,HL,DE 40 A 44 AÑOS,40.460960,-3.699569,0.518616,lejos
98,98,14/01/2014,DE 11:00 A 11:59,MARTES,LATINA,CALLE DE GUAREÑA - CALLE DE LUIS CHAMIZO,0,2014/430,NO,NO,...,COLISIÓN DOBLE,TURISMO,CONDUCTOR,MUJER,HL,DE 30 A 34 ANOS,40.386765,-3.765406,1.563193,muy lejos
99,99,02/05/2012,DE 16:00 A 16:59,MIERCOLES,SALAMANCA,CALLE DE DIEGO DE LEON,13,2012/4065,NO,NO,...,COLISIÓN DOBLE,TURISMO,CONDUCTOR,HOMBRE,HL,DE 21 A 24 AÑOS,40.435117,-3.683953,0.158579,Muy cerca

In [25]:
df['Lejania ocio'].value_counts(dropna=False)

muy lejos    81210
Cerca        43853
Muy cerca    39459
lejos        35499
Name: Lejania ocio, dtype: int64

In [27]:
df.to_csv('Accidentes_y_ocio.csv',sep=';', decimal='.', index=False)